### ISSUE TITLE
Replace "piggy bank" with money jar artwork

### ISSUE THREAD

**Issue by marlitas** [phetsims/number-line-operations#100]
The piggy-bank image was switched out for NLI, and now NLO needs some layout and sizing updates to fit with the new artwork

**Comment by amanda-phet** [comment]
Screen artwork is in. Let me know when it's ready for review.

**Comment by marlitas** [comment]
This is ready for review on main. Let me know if you want to adjust anything. If not, feel free to close!

**Comment by amanda-phet** [comment]
The screen icon looks great to me. 

I do have some concerns about the black stroke on the text on the money bank making it hard to read. 
<img width="89" alt="image" src="https://github.com/phetsims/number-line-operations/assets/7852916/f39e0e73-bd3a-4a86-873d-1d54a59346f9">

**Comment by amanda-phet** [comment]
@marlitas and I played with the stroke, font size, and minus sign, and I think it looks as readable as possible now.

**Comment by marlitas** [comment]
@amanda-phet and I agreed this is ready to close.
