### ISSUE TITLE
Money Bag Labels

### ISSUE THREAD

**Issue by marlitas** [phetsims/number-line-operations#102]
Will track the changes to the money bag labels. We decided to make them all the same width.

**Comment by marlitas** [comment]
This is ready for review. Over to @amanda-phet

**Comment by amanda-phet** [comment]
They look good to me! Should we leave this open for QA to test?

**Comment by marlitas** [comment]
I think it should be fine, I just wanted an issue to track the commit. I'll go ahead and close it. Thanks!
