### ISSUE TITLE
Text overlaps when Equals button is pressed

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-line-operations#103]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.1

**Browser**
Safari 17.1

**Problem description**
For https://github.com/phetsims/qa/issues/1007, on the Operations screen, when I press the equals button in the Net Worth panel, the operation isn't replaced by the total. Instead, the total overlaps the operation. 

**Steps to reproduce**
1. On the Operations screen, press the blue Down Arrow button to add $100
2. Press the equals sign in the Net Worth panel

**Visuals**
<img width="296" alt="Screenshot 2023-11-30 at 5 35 44 PM" src="https://github.com/phetsims/number-line-operations/assets/87318828/01304523-aeac-4d57-8c07-46e790e0994f">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Operations‬
URL: https://phet-dev.colorado.edu/html/number-line-operations/1.1.0-dev.2/phet/number-line-operations_all_phet.html
Version: 1.1.0-dev.2 2023-11-30 16:42:13 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15
Language: en-US
Window: 1293x710
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
The overlap also occurs if you grab the dark blue ball and move it along the number line. 

https://github.com/phetsims/number-line-operations/assets/87318828/0f15c3de-fbb3-4cc2-b66d-be80fba5059c

**Comment by marlitas** [comment]
I think this was fixed with the same commits that fixed https://github.com/phetsims/number-line-operations/issues/104. @Nancy-Salpepi can you check if all is working as you'd expect on main? Feel free to close if all looks well.

**Comment by Nancy-Salpepi** [comment]
No more overlap! Closing.
