### ISSUE TITLE
Value doesn't return to 0 with Reset All 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-line-operations#104]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.1

**Browser**
Safari 17.1

**Problem description**
For https://github.com/phetsims/qa/issues/1007, on the Operations Screen, pressing reset all will return the Net Worth to 0 + 100 instead of 0. On the Generic Screen, the value doesn't reset to 1. 

**Steps to reproduce**
1. On the Operations Screen, add any value (positive or negative) using the Blue Down Arrow 
2. Press Reset All

**Visuals**
Net Worth Screen:

https://github.com/phetsims/number-line-operations/assets/87318828/fd76050f-41a3-4db8-8c3e-2b5ded3332b6

Generic Screen:
<img width="311" alt="Screenshot 2023-11-30 at 7 21 15 PM" src="https://github.com/phetsims/number-line-operations/assets/87318828/1b3e93f1-3d86-479f-a3a8-bfc37b63ea1e">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Operations‬
URL: https://phet-dev.colorado.edu/html/number-line-operations/1.1.0-dev.2/phet/number-line-operations_all_phet.html
Version: 1.1.0-dev.2 2023-11-30 16:42:13 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15
Language: en-US
Window: 1293x710
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
If the dark blue ball was dragged along the number line (for example to -500), that value will still be there on Reset All (the overlapping of values is reported in https://github.com/phetsims/number-line-operations/issues/103). 
<img width="375" alt="Screenshot 2023-11-30 at 6 58 40 PM" src="https://github.com/phetsims/number-line-operations/assets/87318828/0f931a83-6d5d-4150-b7c1-beb17de158f2">

**Comment by Nancy-Salpepi** [comment]
I see the same thing with the eraser button too.

**Comment by marlitas** [comment]
This should now be fixed on main. @Nancy-Salpepi can you check and see if the reset functionality is now working as expected?

**Comment by Nancy-Salpepi** [comment]
This looks good now on main!
