### ISSUE TITLE
Some words don't immediately change when switching locale

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-line-operations#107]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.2

**Browser**
Safari 17.1.2

**Problem description**
For https://github.com/phetsims/qa/issues/1014 and similar to what was reported in https://github.com/phetsims/number-line-distance/issues/84:
On the Operations Screen, the words "asset" and "add" (when the value is 0) don't immediately change when switching locale. 

**Steps to reproduce**
1. On the Operations Screen, increase the value to be added to 200 so that the statement "add asset of $200" appears.
2. Change locales -- the word "asset" will still be in English 
3. Increase the value to be added to 300 --the word "asset" will now be in the selected language
4. Switch to the second operation in the carousel-- the word "asset" is still in English
5. Decrease the value to $0-- it will say "add" in English
6. Press the "-" and then the "+" -- the word "add" will now be in the selected language

**On main I can only reproduce the first part. I don't see the issue with the word "add"**

**Visuals**

https://github.com/phetsims/number-line-operations/assets/87318828/2f3b636e-fcc3-4b91-b844-013b4f2b1c6a

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Mstari wa Namba: Matendo‬
URL: https://phet-dev.colorado.edu/html/number-line-operations/1.1.0-rc.1/phet/number-line-operations_all_phet.html
Version: 1.1.0-rc.1 2023-12-08 00:58:37 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.2 Safari/605.1.15
Language: en-US
Window: 1403x710
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
It also happens with the word "debt" in this rc and on main. 
<img width="681" alt="Screenshot 2023-12-14 at 10 19 42 AM" src="https://github.com/phetsims/number-line-operations/assets/87318828/2004ab4f-8bfa-422e-8e27-ef8e2b0b7f4e">

**Comment by marlitas** [comment]
Fixed above. Ready to cherry pick.

**Comment by Nancy-Salpepi** [comment]
Not completely fixed in rc.2. 
The word "add" will still be in English when the amount is 0.

Steps: 
1. On the Operations screen change locale (ex. Italian)
2. Decrease the value to 0 -- it says "Add 0€"

**Comment by marlitas** [comment]
Interesting... I'm unable to reproduce this on main, but I very clearly see it happening in the RC. Let me see if I missed a commit somewhere...

**Comment by marlitas** [comment]
Ready to cherry pick

**Comment by Nancy-Salpepi** [comment]
The "Add 0" problem has been fixed!
Now that the text is correct, it makes it easy to see that it isn't centered immediately after switching locales. This was hard to see in rc.1 when it was still 2 different languages (I should have noticed in rc.2....sorry). 

https://github.com/phetsims/number-line-operations/assets/87318828/55a27dd8-e66e-4207-b633-f90b16fef311

**Comment by Nancy-Salpepi** [comment]
Looks good to me!
Closing 🎉
