### ISSUE TITLE
Panning is buggy

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-line-operations#108]
For https://github.com/phetsims/qa/issues/1014 and also seen in https://github.com/phetsims/qa/issues/1009 and https://github.com/phetsims/qa/issues/1016:

When zoomed in, the screen pans slightly or not at all. This behavior is different than published. 

This video shows the Operations Screen first in the rc version and then in published:

https://github.com/phetsims/number-line-operations/assets/87318828/87d8ae10-a2ad-4cd1-b12c-b893eb9f4ee7

**Comment by jessegreenberg** [comment]
I just saw this go by, Ill take a look as well.

**Comment by Nancy-Salpepi** [comment]
For https://github.com/phetsims/qa/issues/1016 the buggy panning behavior is most evident in the first and third scenes on the Explore Screen, when an object is removed from the bottom panel and dragged upwards.
This isn't seen in published.

**Comment by jessegreenberg** [comment]
Ah, NLO 1.0 is from 2021 and had a totally different implementation for dragging off screen. There used to be bounds along the edge of the screen that would always trigger a pan. Hmm...

**Comment by jessegreenberg** [comment]
The main way to reproduce this is to keep the dev tools closed and try drag beyond the edge of the screen. If you drag off-window (into the dev tools or onto a second monitor), it works just fine because mouse move events continue to fire.

One way to fix this is just to add a bit of padding to the pan deltas used when panning to keep the target on-screen (but not centered, there is plenty of movement in that case).

I tested it in NLO, geometric-optics, and my-soloar-system, and BASE. I think it feels pretty nice! But @Nancy-Salpepi can you please spot check sims where you can do this kind of pan + drag?

@marlitas can you please also review and test?

**Comment by marlitas** [comment]
@jessegreenberg the commit looks very reasonable and the panning behavior seems much better in my testing. I would be more comfortable to fully sign off after @Nancy-Salpepi is able to take a look as well though.

**Comment by Nancy-Salpepi** [comment]
looking now!

**Comment by Nancy-Salpepi** [comment]
@jessegreenberg and @marlitas in Number Line: Distance, in the first scene of the Explore screen, if I move the character along the sidewalk, the screen doesn't pan. I have to lift the character off the sidewalk first for panning to happen. 

Similarly, in the third screen, the screen pans if I move a character anywhere BUT in the "altitude scene" itself--no panning happens there. 

I'll keep looking to see if I notice anything else.

**Comment by Nancy-Salpepi** [comment]
I see the same issue above in the non-number line screens/screens in Number: Line Integers. 

All looks good in CaV, GO, Function Builder, CCK-AC & Density.

**Comment by jessegreenberg** [comment]
Awesome - Thanks for the test @Nancy-Salpepi. Those are good finds, but luckily unrelated to this change. They are specific to the way the sim is controlling movement when controlling a number line point. So I believe this change is good for NL:O release and ready to cherry-pick.

@marlitas back to you. Do you agree this change is good to cherry-pick for NL:O?  How should we track/investigate this NL:I/NL:D issue? Are those sims close to publication as well?

**Comment by marlitas** [comment]
Ahh that's unfortunate, I was hoping it would fix all of them. Yes we can have this as a cherry-pick specifically for NL:O.

@jessegreenberg NL:I and NL:D are also close to publication (both in RC as well). I'll create an issue in each. So it seems like each fix might be implementation specific?

**Comment by marlitas** [comment]
I'll mark this as ready for cherry pick for NLO. I created the other two issues and assigned you to both @jessegreenberg. I'll take an initial look as well as time allows today.

**Comment by Nancy-Salpepi** [comment]
looks good in rc.2
Closing!
