### ISSUE TITLE
Operation description can be cut off in smaller window sizes 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-line-operations#110]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.2

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1014 on the Operations screen:
In the iframe version and when making my window size smaller, the statement "Add asset of XXX" can be cut off when it appears on the far right or left side of the screen.

**Steps to reproduce**
In the iframe version (or by making your screen narrower):
1. On the Operations screen, increase Initial Net Worth to $700.
2. Add Asset of $700
3. Change locale to Bengali or Turkman --text goes off screen
4.  Press Reset All (but stay in that locale)
5. Decrease initial Net Worth to -$800
6. Add a debt of $400 --text goes off screen
7. Switch back to English--text is initially offscreen until you change a value

**Visuals**
<img width="452" alt="Screenshot 2023-12-14 at 3 25 26 PM" src="https://github.com/phetsims/number-line-operations/assets/87318828/0a709c59-660c-4249-b77c-2a2a43281a16">

<img width="194" alt="Screenshot 2023-12-14 at 3 49 36 PM" src="https://github.com/phetsims/number-line-operations/assets/87318828/45dd6fab-980b-4886-8bfa-9f75246652c5">

**Comment by Nancy-Salpepi** [comment]
Similarly, in "normal" window sizes the operation description is initially off-center when switching locale. Changing the value or moving the sphere fixes things. 

Happens with many locales, but easy to see with ?stringTest=dynamic:
1. Press the blue down arrow button to add 100 
2. Press the right arrow key to double the text
3. Move the dark blue sphere.

Initially:
<img width="271" alt="Screenshot 2023-12-18 at 6 36 04 PM" src="https://github.com/phetsims/number-line-operations/assets/87318828/db99c66d-2bdd-4a1a-977a-8d3fbbe9021a">
After moving sphere:
<img width="271" alt="Screenshot 2023-12-18 at 6 36 35 PM" src="https://github.com/phetsims/number-line-operations/assets/87318828/07c60505-0c0a-425f-b80a-082b561fc4d3">

**Comment by marlitas** [comment]
Addressed above. Ready to cherry pick.
