### ISSUE TITLE
Overlapping pointer areas

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-operations#112]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/qa/issues/1014
In the RC, the pointer areas for the bike and ring overlap in the toolbox slightly. They do not in the published version. Minor issue.

**Visuals**
![overlap](https://github.com/phetsims/number-line-operations/assets/41024075/5db1b0eb-ebcf-4f11-aa36-ee9f601b7353)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Operations‬
URL: https://phet-dev.colorado.edu/html/number-line-operations/1.1.0-rc.1/phet/number-line-operations_all_phet.html?showPointerAreas
Version: 1.1.0-rc.1 2023-12-08 00:58:37 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0
Language: en-US
Window: 1536x731
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0))
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by marlitas** [comment]
Fixed above. Ready for cherry-pick

**Comment by Nancy-Salpepi** [comment]
This is fixed in rc.2
Closing.
