### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by marlitas** [phetsims/number-line-operations#115]
From https://github.com/phetsims/qa/issues/1014 there appears to be a memory leak.

![image](https://github.com/phetsims/number-line-operations/assets/42476338/da3269e4-8be9-470a-94b4-3f7f0e192363)

**Comment by Nancy-Salpepi** [comment]
Memory test looks good in rc.2 
Closing
<img width="397" alt="Screenshot 2024-01-05 at 1 42 23 PM" src="https://github.com/phetsims/number-line-operations/assets/87318828/266bcf47-d2e6-4295-97b3-d87fb2675293">
