### ISSUE TITLE
Text doesn't fit on objects in some locales

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-line-operations#118]
For https://github.com/phetsims/qa/issues/1027

This wasn't present in rc.1 but is in rc.2 and rc.3:

On the Net Worth Screen, in some locales the text continues past the objects:

Here is Romana in rc.3:
<img width="184" alt="Screenshot 2024-01-10 at 9 41 52 AM" src="https://github.com/phetsims/number-line-operations/assets/87318828/3a7bdb70-02e1-492f-98f1-f2a00cabaa9b">

Here is Romana in rc.1:
<img width="184" alt="Screenshot 2024-01-10 at 9 42 19 AM" src="https://github.com/phetsims/number-line-operations/assets/87318828/dc269d70-bf77-40d5-a21a-96849f7225d4">

**Comment by KatieWoe** [comment]
Even when it doesn't go off the object, it isn't centered if the $ sign is translated to a longer symbol.
![image](https://github.com/phetsims/number-line-operations/assets/41024075/41b00136-de52-4f42-8daf-9743ee0258e8)

**Comment by marlitas** [comment]
The above commit fixes both issues. This is ready for cherry-pick

**Comment by Nancy-Salpepi** [comment]
Looks good in rc.4! 
Closing 🎉
