### ISSUE TITLE
Address `strictAxonDependencies: false`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#119]
In https://github.com/phetsims/axon/issues/441 `strictAxonDependencies` was turned on for all sims.

In TotalValueAccordionBox:

```ts
      readoutStringProperty = new PatternStringProperty( NumberLineOperationsStrings.totalValuePatternStringProperty, {
        totalString: options.labelText,
        totalValue: totalValueProperty
      }, {
        maps: {
          totalValue: value => signProperty.value + Math.abs( value ).toString( 10 )
        }
      } );
```

`signProperty` is a missing dependency.  One way this could be resolved is by replacing `new PatternStringProperty` with `new DerivedStringProperty( [  NumberLineOperationsStrings.totalValuePatternStringProperty, totalValueProperty, signProperty. ], ... )`.

In the meantime, https://github.com/phetsims/number-line-operations/commit/f2f4fb0369f1998de9b9451adfdf607a2a8d0c50 adds `strictAxonDependencies: false` to this PatternStringProperty to opt out.

**Comment by jbphet** [comment]
I've addressed this using `DerivedStringProperty` as suggested by @pixelzoom above.  It worked out well, and allowed me to consolidate the code such that there is only one path where the readout string Property is created.  Closing.
