### ISSUE TITLE
potential infinite loop in NumericalExpressionAccordionBox

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#12]
Noted while working on https://github.com/phetsims/natural-selection/issues/118.  

This is a potential infinite loop in NumericalExpressionAccordionBox.js:

```
    numericalExpression.boundsProperty.link( () => {
      numericalExpression.centerX = CONTENT_DIMENSIONS.width / 2;
      numericalExpression.top = 0;
    } );
```

When `numericalExpression.centerX` and `numericalExpression.top` are set, that changes `numericalExpression.bounds`.  The solution is to observe `numericalExpression.localBoundsProperty`.

**Comment by jbphet** [comment]
I changed the code to monitor local bounds instead and tested in NLO.  All looks good.  Thanks @pixelzoom for pointing this out.  Closing.
