### ISSUE TITLE
Colors of points

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-operations#13]
I need to provide @jbphet with colors for points. 

Net Worth/Chips: The "initial" blue color should be different than the current one. 

Operations/Generic: I want the feeling of a gradient so there is a clear progression from light to dark, but the current blue shade doesn't work well. So consider slightly different hues of blue as well.

**Comment by amanda-phet** [comment]
@jbphet please use the following colors: 
![image](https://user-images.githubusercontent.com/7852916/87331279-f33bc180-c4f6-11ea-9e98-3141b50c1d84.png)


#0000C4 for the "most recent point"
#4069FF for the previous point
#64A3FF for the initial point

Here it is in context: 
After two operations
![image](https://user-images.githubusercontent.com/7852916/87331307-fd5dc000-c4f6-11ea-8c61-cfdf33075972.png)

After one operation
![image](https://user-images.githubusercontent.com/7852916/87331382-19616180-c4f7-11ea-937c-28cf122ccf8d.png)

No operations
![image](https://user-images.githubusercontent.com/7852916/87330772-48c39e80-c4f6-11ea-8034-11e41af45386.png)


Please use these colors on the Net Worth, Operations, Chips, and Generic screens. 

![image](https://user-images.githubusercontent.com/7852916/87331440-3007b880-c4f7-11ea-9ed3-dfbe907e8942.png)

**Comment by jbphet** [comment]
@amanda-phet - what shall we do for the magenta-ish points used on the 2nd number line on the "Generic" screen?

**Comment by amanda-phet** [comment]
#b400ce
#f533ff
#ff85ff

Thanks!

**Comment by jbphet** [comment]
@amanda-phet and I discussed a modification to what is described above where the start point, i.e. the point from which the first operation originates, is the darkest and remains so, and the subsequently added end points (at the end of each operation) are darker.  I've implement this and it is available in https://phet-dev.colorado.edu/html/number-line-operations/1.0.0-dev.9/phet/number-line-operations_en_phet.html, and the point controller colors are now updated as well.

@amanda-phet - please review and let me know what you think.

**Comment by amanda-phet** [comment]
I think this is working nicely. I think we need to tweak the colors a tiny bit. 

The medium pink should be #ef29ff and the light pink should be #fb71ff. These colors have improved contrast against the background (although it's not great.. but it's very difficult to get all these shades plus excellent contrast) and also improved color-blind performance.

**Comment by jbphet** [comment]
@amanda-phet - would it help with contrast if we were to add a stroke to the points?  That feature isn't supported at the moment, but could be added.

**Comment by jbphet** [comment]
@amanda-phet - I've updated the pink colors as recommended above.  Please let me know if you'd like a dev version to try out or for interviews.

**Comment by amanda-phet** [comment]
>would it help with contrast if we were to add a stroke to the points? That feature isn't supported at the moment, but could be added.

The issue is more the legibility of the label above the point, but I think it is looking alright as it is. The colors interviewed well today so I think we can close this issue.
