### ISSUE TITLE
Miscellaneous to-do 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-operations#15]
- [x] make "Loan" text translatable 
- [x] re-color number-line bag to be red and yellow instead of red and green

**Comment by jbphet** [comment]
@amanda-phet - I'll need revised artwork from you where the loan (debt) artwork doesn't have the word "Loan" on it.

**Comment by amanda-phet** [comment]
I put the artwork in #8 . Thanks!

**Comment by jbphet** [comment]
These two items are complete.  @amanda-phet - please take the latest version for a test drive and close if all looks good.

**Comment by amanda-phet** [comment]
Bag colors and Loan text look good! I tested with `?stringTest=double` as well and I thought it looked fine. `?stringTest=long` was a bit out of control, but I'll leave that to QA ;)
