### ISSUE TITLE
Memory test for phet brand

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-operations#17]
This is one of the standard GitHub issues required by the code-review checklist, see https://github.com/phetsims/number-line-operations/issues/16.  I'll run the test and document the results when we're getting a little closer to the first major dev test or code review.

**Comment by jbphet** [comment]
First run: Tested unbuilt on master, SHA was 26884ebbd00bed8485a295714b03dbcd5d488de6, common code was whatever was on master today, 12/2/2020.

Test | Memory Usage (MB)
--- | --- 
Immediately after load, no fuzzing | 26.8 MB
Load, visit each screen, then back to home screen, no fuzzing | 26.2 MB
After 1 min of fuzz | 33.8
After 2 min of fuzz | 37.0
After 3 min of fuzz | 39.6
After 4 min of fuzz | 41.8
After 5 min of fuzz | 44.7
Stop fuzz, reset each screen, go to home screen | 45.3

For reference, I used the command `phet.chipper.queryParameters.fuzz=false` in the console to stop the testing.

It looks like there is a bit of memory leaking, though not a tremendous amount.  I compared the snapshots corresponding to the 2nd and last entries in the table above to see what got created but not released during that testing.  When I scroll down the list,  `PointController` and `PointControllerNode` instances are the first sim-specific instances I see, and there is a net gain of 406 of these.

Here's a screenshot of the comparison with the part that likely needs to be addressed circled:

![image](https://user-images.githubusercontent.com/3082831/100950603-ed587400-34c9-11eb-8679-27bdcf09df6e.png)

**Comment by jbphet** [comment]
Instances of `PointController` were indeed being leaked.  This was due to a linkage to the `valueProperty` of the end points in the model for the "Generic" screen.  The dispose function in `PointController` has now been updated to release all points, and a small-scale test appeared to show that this change has fixed this leak.  I'll repeat the test from above to see where we are now.

**Comment by jbphet** [comment]
For the next text, I used unbuilt on master, SHA was 26884ebbd00bed8485a295714b03dbcd5d488de6, common code was whatever was on master today, 12/2/2020.

Test | Memory Usage (MB)
--- | --- 
Immediately after load, no fuzzing | 26.7
Load, visit each screen, then back to home screen, no fuzzing | 26.3
After 1 min of fuzz | 32.6
After 2 min of fuzz | 33.2
After 3 min of fuzz | 33.2
After 4 min of fuzz | 33.5
After 5 min of fuzz | 33.5
Stop fuzz, reset each screen, go to home screen | 33.4

This seems like pretty decent behavior, since the amount of memory used seems to reach a steady-state value around 33 MB fairly quickly and stays there, and that's a reasonable value.  I also don't see any sim-specific leakage when I compare the last snapshot to the second one.

There is one thing I want to follow up on though: There seems to be a number of audio-related classes that are being allocated and not released.  Sound is not enabled for this sim, so my guess is that common-code components are trying to play their sounds, audio source buffers are being created as a result, but they are never being freed since they are not actually being played.

**Comment by jbphet** [comment]
I fixed the issue with leaking audio-related objects in https://github.com/phetsims/tambo/issues/130 and verified that I don't see the problem anymore.  I'm not going to take the time to write up the results as I did in the previous comments, but the bottom line was that after 5 minutes of fuzz testing the memory was stable at 31.4 MB.

For now, I think we're in good shape on this.  I'm going to leave the issue open but unassigned for now, and will revisit right before the first RC.

**Comment by jbphet** [comment]
On second thought, I should leave it assigned to me but deferred, and undefer it and re-test just before the first RC.  That makes more sense.

**Comment by pixelzoom** [comment]
The CRC says:
> - [ ] Does a heap comparison using Chrome Developer Tools indicate a memory leak? (Describing this process is beyond the scope of this document.) Test on a version built using `grunt --minify.mangle=false`. Compare to testing results done by the responsible developer.

I see no evidence in the above comments that memory testing was done with a built version.  All comments refer to "unbuilt". 

@jbphet ?

**Comment by pixelzoom** [comment]
For #35 code review, I confirmed memory test results using a version built using `grunt --minify.mangle=false --brands=phet`.   Results do not indicate any memory leaks, see below.

Test | Memory Usage (MB)
--- | --- 
Immediately after load, no fuzzing | 26.5
Load, visit each screen, then back to home screen, no fuzzing | 25.8
After 1 min of fuzz | 31.8
After 2 min of fuzz | 32.9
After 3 min of fuzz | 32.9
After 4 min of fuzz | 32.7
After 5 min of fuzz | 33.3

**Comment by jbphet** [comment]
The QA team says that things look acceptable in the first RC, see https://github.com/phetsims/QA/issues/600#issuecomment-769414647.  Closing.
