### ISSUE TITLE
Performance test and sign-off

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-operations#18]
This is listed as a "standard GitHub issue" in the code-review checklist. The lead designer must sign off on performance.  I'll do my own testing and then will assign when we're getting a little closer to release.

**Comment by jbphet** [comment]
Hey @amanda-phet - this is a standard issue that we generally set up for code review, and I apologize for not assigning it to you earlier.  This sim doesn't have a lot of performance intensive attributes, so I don't think that there is much of a question here, but I thought it would be good for you to verify that the performance is adequate.  You can test on version https://phet-dev.colorado.edu/html/number-line-operations/1.0.0-rc.2/phet/number-line-operations_en_phet.html.

**Comment by amanda-phet** [comment]
I don't have any concerns about performance.
