### ISSUE TITLE
Review pointer areas

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-operations#19]
This is listed as a "standard GitHub issue" in the code-review checklist.  I'll take a pass through and then will assign to @amanda-phet when we're getting a little closer to a serious dev test.

**Comment by jbphet** [comment]
@amanda-phet - Can you please check the pointer areas on https://phet-dev.colorado.edu/html/number-line-operations/1.0.0-dev.13/phet/number-line-operations_en_phet.html?showPointerAreas?  If all is well, this can be closed, otherwise assign back to me with a description of any changes that are needed.

**Comment by amanda-phet** [comment]
Looks good to me!
