### ISSUE TITLE
Finalize credits

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-operations#2]
...so we don't forget before publication.

**Comment by jbphet** [comment]
@KatieWoe - Since we're now entering the final stages before initial publication, can you please provide me with a list of all members of the QA team (other than yourself) that have performed testing on this sim?

**Comment by KatieWoe** [comment]
Liam Mulhall, Devon Quispe, Brooklyn Lash, Logan Bray

**Comment by jbphet** [comment]
I've added the people from the list above and verified it in the "About" dialog on RC.3.  Closing.
