### ISSUE TITLE
Implement better handling for overlapping points on the generic screen

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-operations#20]
This is a sister issue to https://github.com/phetsims/number-line-distance/issues/6, where the general problem and potential solutions were first described.

As of this writing, overlapping points in the generic screen look like this:

![image](https://user-images.githubusercontent.com/3082831/97500506-53833180-1935-11eb-9f75-8edc4776ee84.png)

Note that you can barely tell that the points are overlapping, and on the top point can be grabbed and manipulated from this state.

In a recent design meeting for "Number Line: Distance" we discussed handling overlapping points like this by either extending the handling of the point controllers so that they don't overlap, or by expanding the ones that are further back in the z-order so that their bounds extends outside of the bounds of the ones that are more forward in the z-order.  Whatever solution we come up with should apply to both sims.

**Comment by jbphet** [comment]
@amanda-phet - I think the design team talked about this in a review meeting a month or two ago, and decided that since not much development has been done on this feature for number-line-distance, we wouldn't try to integrate it into number-line-operations.  However, we apparently didn't update this issue at the time.  Is that your recollection too and, if so, can we close this?

**Comment by amanda-phet** [comment]
It's ok that the point handles overlap, but for some reason I thought this issue was about the opacity of the point label. I will look for that issue. For this one though, I'm not concerned about the handles overlapping the way they do.
