### ISSUE TITLE
Make the operation description, arrow, and previous point fade away

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-operations#21]
On the Chips and Net Worth screens, an operation description, arrow, and point all appear when something is added to or removed from the bags. 

![image](https://user-images.githubusercontent.com/7852916/98304446-3d045800-1f7d-11eb-80a1-735b0e0db68b.png)

After a period of time (maybe 5 seconds), we'd like the operation description, operation label, arrow, and previous point to fade away. At this time, the terminal point should also change to the dark blue (initial point) color. 
![image](https://user-images.githubusercontent.com/7852916/98304416-2b22b500-1f7d-11eb-9ec9-fc0f85711a89.png)

**Comment by jbphet** [comment]
@amanda-phet - I've added this feature.  I plan to make some refinements to the code, but it would be good if you could take a look at the behavior first and let me know if this is close to what we're after.  It's available on master, let me know if you need a dev version instead.

**Comment by amanda-phet** [comment]
Looks good! 

Can you make the wait time a bit longer before stuff fades away? I'm not sure if I want it twice as long, or somewhere in between, but let's start with twice as long.

**Comment by jbphet** [comment]
The design team reviewed this and made adjustments during the 11/20/2020 review meeting.  It should be good to go.  Closing.
