### ISSUE TITLE
Operation control design

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-operations#22]
Following up with 11/5/20's meeting discussion: There are 2 potential changes we are considering to the operation control (carousel). 
1. Auto-swipe when the user changes an operation via point controller so that the operation control is in sync with the number line changes
2. Do not auto-swipe to the second operation once the user enters the first operation. Instead, the user will manually click to the next page of the carousel to apply another operation. 

What if we did something like this… the “carousel” would not auto-scroll to the next operation (the user would need to click the arrow), but it would auto-scroll when the user manipulates that operation via the point drag handler. To me, removing the heaviness of the carousel helps a lot. I think it keeps the focus on the numerical expression and the number line, but it also keeps the control in sync with the users actions.

![image](https://user-images.githubusercontent.com/7852916/98406614-88753f80-202b-11eb-8b4c-ed6a27994ba0.png)

![image](https://user-images.githubusercontent.com/7852916/98406628-8f9c4d80-202b-11eb-8d45-bdf392c5d023.png)

I realize there is a complication here because this is not the common code carousel anymore, but I’d really like to consider something in this direction. Also open to new button ideas, I just started with what we have already.

Assigning to the design team to consider and add ideas in this issue.

**Comment by ariel-phet** [comment]
@amanda-phet I generally like the thought of reducing visual weight, but right now all those buttons feel less grouped and a bit of "button soup". Perhaps you could stick with the carousel, but just keep very lightweight strokes and the same/similar background color as you have above. I like the interaction suggestions.

**Comment by kathy-phet** [comment]
@amanda-phet - I'm wondering what it would look like if it was sort of like what Ariel describes. Maybe achieved by making the carousel white background quite tranparent, or picking a color just a shade lighter than the background of the sim itself. Maybe if you do that, it won't need a stroke?

**Comment by amanda-phet** [comment]
Here is the background at 50% opacity:
![image](https://user-images.githubusercontent.com/7852916/98743519-6fdb9100-236d-11eb-8b5c-e827ccdd8a11.png)

Here is reduced opacity with a gray stroke:
![image](https://user-images.githubusercontent.com/7852916/98743481-618d7500-236d-11eb-873e-96951abe3c1e.png)

Reduced opacity and a stroke to match the gray button:
![image](https://user-images.githubusercontent.com/7852916/98743638-9d283f00-236d-11eb-86b7-405804644a7e.png)

Thoughts? I think I like the middle option, but would be interested in pursuing more options.

**Comment by amanda-phet** [comment]
Oh, and no stroke, with 70% opacity background:
![image](https://user-images.githubusercontent.com/7852916/98743805-de205380-236d-11eb-80d8-65f54c082ae2.png)

**Comment by amanda-phet** [comment]
Leaning toward this version: 
![image](https://user-images.githubusercontent.com/7852916/99005427-05a62600-24fe-11eb-9268-f9d8baee7e49.png)

It is definitely muted compared to the original, but could also stand out more than I want. We will look for interviews. 

- [ ] background 50% opacity
- [ ] "other" button is invisible when disabled 
- [ ] stroke color is blue to match the "go" button
- [ ] we might want to tweak the size of the picker. Let's do this next week at design.

**Comment by amanda-phet** [comment]
All of these changes seem addressed, but @jbphet will make a few more tweaks: 

- [x] Reduce space between operation buttons, picker, and go button
- [ ] Move page control buttons on "pink" controller to the top
- [ ] Make the second number line control pink (stroke and button) - Generic screen

**Comment by jbphet** [comment]
This was reviewed with the design team at today's review meeting, and some changes were made, and it was also recommended that the carousel stroke and shift buttons be coordinated with the entry control button (right now they are all blue).  Also, the page control buttons should be moved to the top for the lower control.

Screenshot:

![image](https://user-images.githubusercontent.com/3082831/99731875-c0dd3a80-2a7b-11eb-9c90-bca1d92e7207.png)

**Comment by jbphet** [comment]
@amanda-phet - I think the latest dev version has the behavior as described above and as discussed in the most recent review meetings.  Please take a look and either close or assign back to me if there is more work to be done.

Link: https://phet-dev.colorado.edu/html/number-line-operations/1.0.0-dev.10/phet/number-line-operations_en_phet.html

**Comment by amanda-phet** [comment]
It all looks like it is there! Looking forward to seeing how it goes in interviews. I will open a new issue if I need further changes.
