### ISSUE TITLE
Make the alignment of the scene selection buttons and accordion box match NLI

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-operations#24]
These aren't aligned, if you look at the sims side-by-side.

![image](https://user-images.githubusercontent.com/7852916/99735067-33044e00-2a81-11eb-9e0a-71b159333079.png)

Please shift the scene selection buttons and accordion box in Number Line: Operations to match the placement of these buttons in Number Line: Integers. I'm fine with these being a static placement, since the aren't currently aligned to anything in the NLO sim (that I'm aware of). This might end up being a 6px shift down for the scene selection buttons and 14px shift down for the accordion box.

**Comment by jbphet** [comment]
I ended up changing more than just the layout, because when I compared NLO and NLI closely, it turned out that their reset-all buttons were in different places.  So, first off, I fixed that, then made the arrow parameters and selector button sizes the same, and then made the layouts match.

**Comment by jbphet** [comment]
@amanda-phet - please check this out on https://phet-dev.colorado.edu/html/number-line-operations/1.0.0-dev.10/phet/number-line-operations_en_phet.html and, if it all looks good, please close this issue.  If not, please assign back to me with your suggestions.

**Comment by amanda-phet** [comment]
The alignment of the scene selection buttons and combo box look good. 

The reset-all buttons seem to be in different locations... did you change the location in NLO or NLI?

**Comment by jbphet** [comment]
I changed NLO to match NLI, which also matched Natural Selection.  I used Natural Selection as the arbitrator since it was a recently published sim.

**Comment by amanda-phet** [comment]
OK, well this is what I'm seeing with NLO-dev.10 and the published version of NLI.

![image](https://user-images.githubusercontent.com/7852916/100170692-7694f880-2e83-11eb-94e1-b99a55303845.png)

So the reset-all buttons don't seem to be lined up. I noticed it in the browser but did this overlay to show what I'm seeing. Can you double-check? I also checked master just to be sure, and master matches what I see in NLO-dev.10.

**Comment by jbphet** [comment]
The reset button in NLI and NLO on master (*not* on the published version of NLI) are currently aligned with one another and are consistent with other recently published sims.  I plan to republish NLI at the same time that we do NLO so that this, and other things (such as the checkbox fonts) stay consistent between sims.  That being said, I'm happy to move the button if needed to match the published version if you think that is better for some reason.

**Comment by amanda-phet** [comment]
These are aligned on master! Thanks.
