### ISSUE TITLE
Reset should restore initial values to operation entry controls

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-operations#25]
On the current master version, pressing the Reset All button on the "Operations" or "Generic" screens causes the operation entry control values to go to zero.  They should go to their original values instead.

Pressing the number-line-erase button should continue to set them to zero.

**Comment by jbphet** [comment]
This is implemented.  @amanda-phet - please check this in https://phet-dev.colorado.edu/html/number-line-operations/1.0.0-dev.10/phet/number-line-operations_en_phet.html and verify that we're happy with the behavior.  If so, please close, if not, assign back to me with any suggestions.

**Comment by amanda-phet** [comment]
It appears to be working just right. Thanks!
