### ISSUE TITLE
Change the simplify checkbox into a momentary button

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-operations#30]
![image](https://user-images.githubusercontent.com/7852916/101834838-185d4c00-3af8-11eb-8176-cceda695dad8.png)

This button should be disabled until the user has a series of operations that can be simplified (which means they have a negative operand, e.g. - -3 or + - 3)

**Comment by amanda-phet** [comment]
Reviewed this during 12/17/20 design meeting and functionally the buttons are working great!

**Comment by amanda-phet** [comment]
@jbphet and I discussed some options and wanted to be sure everyone was ok with these button locations. Can @kathy-phet and @ariel-phet please confirm that this looks ok? 

<img width="846" alt="Screen Shot 2020-12-18 at 12 31 34 PM" src="https://user-images.githubusercontent.com/7852916/102654534-e66a6c00-412d-11eb-8292-90856c7b22f4.png">

<img width="845" alt="Screen Shot 2020-12-18 at 12 31 51 PM" src="https://user-images.githubusercontent.com/7852916/102654548-ec604d00-412d-11eb-9368-36b3d014dbd1.png">

**Comment by ariel-phet** [comment]
Looks good to me!

**Comment by amanda-phet** [comment]
This has been approved for a while so we can close it.
