### ISSUE TITLE
Change the Operations screen to have point controllers

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-operations#32]
We'd like the Operations screen to have point controllers that follow the same rules as the Generic screen. If the user drags a point controller, it only changes the operand (the value in the number picker), and never the operation. 

![image](https://user-images.githubusercontent.com/7852916/101835477-13e56300-3af9-11eb-9713-4f460b6f7bbd.png)

**Comment by amanda-phet** [comment]
Reviewed in 12/17/20 design meeting and this added functionality is working well and looks great.

**Comment by jbphet** [comment]
Reviewed and approved in the 12/17/2020 design meeting.
