### ISSUE TITLE
Design team signoff

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-operations#33]
@amanda-phet, @kathy-phet, and @ariel-phet - I've implemented the latest round of changes, and I think this puts us at or near being feature complete.  I thought I'd publish a dev version and have all of you review it and make sure that everyone is good with the current implementation.  Please review https://phet-dev.colorado.edu/html/number-line-operations/1.0.0-dev.11/phet/number-line-operations_en_phet.html and log any design issues below.  If you find functional problems, please create separate issues for those.

**Comment by kathy-phet** [comment]
Looks great to me! I logged one bug.

**Comment by ariel-phet** [comment]
Looks great to me!

**Comment by amanda-phet** [comment]
I think it all looks good, and don't have any more change requests!

**Comment by amanda-phet** [comment]
Ha! Spoke too soon. 

@jbphet when I click the equal button to see the sum, I notice we are using the shorter minus sign. I know I've gone back and forth on the use of this sign, but I think it would look nicer to use the wider minus sign. 

<img width="360" alt="image" src="https://user-images.githubusercontent.com/7852916/103039956-62e6bb80-452f-11eb-8c76-cd3fcad7a7fa.png">

<img width="368" alt="Screen Shot 2020-12-23 at 2 59 11 PM" src="https://user-images.githubusercontent.com/7852916/103039983-772ab880-452f-11eb-88d2-e3571560d301.png">

What do you think?

**Comment by jbphet** [comment]
Updated on master.  @amanda-phet - please verify that the behavior now on master is what we're after.

**Comment by amanda-phet** [comment]
This seems fixed on all screens except Chips. 

![image](https://user-images.githubusercontent.com/7852916/104650222-19434980-5673-11eb-9dc9-2665d1e63771.png)

**Comment by jbphet** [comment]
@amanda-phet - I've made the changes to the indicators used on the "Chips" screen.  Please look the sim over and, if they all look good and you don't see any other design issues, this can be closed.

**Comment by amanda-phet** [comment]
Looks good! Thank you for making that last change.
