### ISSUE TITLE
Is there an asset for every image file?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#36]
Related to #35 code review.... For this CRC item:

> - [ ] Is there a file in assets/ for every resource file in sound/ and images/? Note that there is not necessarily a 1:1 correspondence between asset and resource files; for example, several related images may be in the same .ai file. Check license.json for possible documentation of why some reesources might not have a corresponding asset file.

This sim has 4 .ai files and 23 .png files.   I'm guessing that asset-*.png may originate from asset-debt-artwork.ai.  But for the others, it's not obvious, and it's not document images/license.json.  

Recommended to (1) verify that there is indeed an asset for each .png file, and (2) document in license.json.

**Comment by jbphet** [comment]
I started on this, but my version of Adobe Illustrator is too old to correctly open the .ai files in the asset directory.  @amanda-phet - can you verify that the .ai files contain the drawings that were used to create the image files, and update the `license.json` file in the `images` directory to indicate the file from which each image was created?

**Comment by amanda-phet** [comment]
This is done.
