### ISSUE TITLE
Ordering of checkboxes doesn't match ordering the things they control.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#38]
Noted while working on #35 code review.

Each screen has a set of check boxes in the upper-left that determines what is displayed on the number line. The vertical order of these check boxes doesn't match the vertical order of how these things are displayed, see annotated examples below.  This is imo a slight usability problem -- especially in the Operations screen, when you have 4 checkboxes -- that can be easily corrected. 

<img width="1536" alt="chips" src="https://user-images.githubusercontent.com/3046552/103157888-1c829e00-4775-11eb-9f29-2ef795314069.png">

<img width="1024" alt="operations" src="https://user-images.githubusercontent.com/3046552/103157890-20aebb80-4775-11eb-9221-cf4c8805d71b.png">

**Comment by amanda-phet** [comment]
Let's switch the order of these to be: 

- Operation Descriptions 
- Operation Labels
- Point Labels
- Tick Marks 

For all screens where these are applicable.

**Comment by jbphet** [comment]
This is done.  It affects all screens, because they all had some or all of the checkboxes listed above.  @amanda-phet - please review on master and, if you're good with this, I think we can just close it.

**Comment by amanda-phet** [comment]
This is a nice change. Thanks.
