### ISSUE TITLE
Should "Operation Description" checkbox label be plural?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#39]
Noted during #35 code review.

Each screen has a set of checkboxes in the upper-left corner, example below.  These checkboxes all have plural labels, except for "Operation Description".   Is there a reason why that label is singular?  That checkbox does affect the visibility of all operation descriptions. 

<img width="230" alt="screenshot_786" src="https://user-images.githubusercontent.com/3046552/103157899-50f65a00-4775-11eb-8c20-8881da5f1b01.png">

**Comment by pixelzoom** [comment]
Marking this as "blocks publication" because it would also involve changing the associated string key.

**Comment by amanda-phet** [comment]
Thanks for noticing this @pixelzoom . I think we should make this plural, so it says "Operation Descriptions"

**Comment by jbphet** [comment]
Done.  Closing.
