### ISSUE TITLE
Transparency of labels on number line

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#40]
Noted while working on #35 code review.

Labels on the number line have a white background behind them, with some level of transparency.  I'm wondering it that transparency has been vetted.

For example:
1. Start sim
2. Go to Operations screen
3. Press the "apply operation" button (arrow that points right and down) in the carousel to apply "+ 0"
4. The number line displays what is shown in the screenshot below.

To me, this looks odd.  And I didn't immediately parse it visually.  Should the "300" be more translucent, so you can see the arrow? Are there any other labels that have a similar issue? 

<img width="158" alt="screenshot_787" src="https://user-images.githubusercontent.com/3046552/103157963-ef82bb00-4775-11eb-8450-4bb2b9491c57.png">

**Comment by amanda-phet** [comment]
Yes this is supposed to be the case. For some reason I thought it was being worked on and I can't find the relevant issue, so thank you for creating this one.

**Comment by jbphet** [comment]
@amanda-phet - I've added support for transparent point labels and took a shot at setting an opacity level for these labels on the "Operations" and "Generic" screens.  Please have a look on master and let me know whether this addresses the issue.

**Comment by amanda-phet** [comment]
So I was very confused and I thought the issue here was when '+0' was added twice. I didn't realize the point label was fully opaque all the time. So we cleared that up today for me :) 

@jbphet showed us some different options in the 1/21/21 design meeting and we liked an opacity of 70% for the point label.

**Comment by amanda-phet** [comment]
@jbphet please feel free to assign back to me to review again once you made the final commit.

**Comment by jbphet** [comment]
Commit made, back to you @amanda-phet.

**Comment by amanda-phet** [comment]
The transparency looks good. I don't love how light the labels seem now, but I'm not sure what to do there without making them all the same color, so we will leave them as they are.
