### ISSUE TITLE
Right-align combo box for setting number-line range.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#45]
Noted during #35 code review.

This is admittedly a low-priority nit, but I'll mention it anyway. 

Generic screen has a combo box for setting the number-line range, and it looks like this when the listbox is popped up:

<img width="236" alt="screenshot_796" src="https://user-images.githubusercontent.com/3046552/103158835-b3545800-477f-11eb-9d57-49125a4d53ec.png">

If it were me, I'd change to `align: 'right'`, because I think that (a) numbers should be right aligned, and (b) it more clearly communicates that the bottom choice is a larger range.  Like this:

<img width="257" alt="screenshot_797" src="https://user-images.githubusercontent.com/3046552/103158846-cd8e3600-477f-11eb-8259-f4ac9b866dee.png">

**Comment by amanda-phet** [comment]
Sounds good to me!

**Comment by amanda-phet** [comment]
Can we make this change in number-line-common? So it would impact NLI as well.

**Comment by jbphet** [comment]
Implemented.  Looks nice.  Closing.
