### ISSUE TITLE
potential problems with string keys

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#47]
Related to code review #35, this issue is for noting potential problems with string keys. 

This issue will be labeled with "blocks-sim-publication", because string keys can't easily be changed after 1.0 publication.

**Comment by pixelzoom** [comment]
- [ ] In #39, I noted that "Operation Description" should likely be plural.  That would result in a change to this string key and value:

```
  "operationDescription": {
    "value": "Operation Description"
  },
```

**Comment by pixelzoom** [comment]
- [ ] In number-line-common-strings_en.json, which I realize is difficult to change at this point:

```
  "range": {
    "value": "{{lowValue}} to {{highValue}}"
  },
```

Elsewhere you've used a "Pattern" suffix on keys that contain placeholders.  And "range" seems awfully general   So I would consider a key like "rangePattern" or "lowToHighPattern".

**Comment by pixelzoom** [comment]
- [ ] For these 2 strings:

```
  "totalPattern": {
    "value": "{{totalString}} = {{totalValue}}"
  },
  "totalCurrencyPattern": {
    "value": "{{totalString}} = {{sign}}{{currencyUnits}}{{totalValue}}"
  },
```

I would inline "Total".  It's not really necessary (or all that useful) to factor out. Including it may make the string easier for translators to find.  And you didn't factor out the multiple occurrences of "Initial" (nor do I think you should.)

The "totalPattern" key could also use a little work, to make it more consistent with "totalCurrencyPattern". Maybe "totalValuePattern"?

So maybe something like:

```
  "totalValuePattern": {
    "value": "Total = {{totalValue}}"
  },
  "totalCurrencyPattern": {
    "value": "Total = {{sign}}{{currencyUnits}}{{totalValue}}"
  },
```

**Comment by pixelzoom** [comment]
- [ ] Wherever you've used placeholder  `{{currencyUnits}}`, you've referred to "currency" in the key name.  This key name is the exception, so perhaps "currencyValuePattern"?

```
  "monetaryValuePattern": {
    "value": "{{sign}}{{currencyUnits}}{{value}}"
  },
```

**Comment by pixelzoom** [comment]
Review of string keys is completed.

**Comment by jbphet** [comment]
All comments addressed, closing.
