### ISSUE TITLE
Incorrect syntax for Property type expressions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#48]
Related to #35 code review.  

Throughout number-line-common and number-line-options, I see type expressions like this:

```js
@param {Property<Range>} selectedRangeProperty
```

My recollection is that we  decided to use `Property.<Range>`, with a dot before the "<".   That syntax conforms to JSdoc, see https://jsdoc.app/tags-type.html.  To confirm, search for "Property.<" vs "Property<" in scenery and other common-code repos.  

That said... I do see other developers using the syntax that is used here, but it's mostly in @jbphet code.  So perhaps a PSA or discussion is needed.  @jbphet Do you mind leading that?

**Comment by pixelzoom** [comment]
Also note in the CRC:

```
Especially in common code, using {Property.<TYPE>} is typically correct, unless some specific feature of the Property subclass is required. 
```

**Comment by pixelzoom** [comment]
Same issue with ObservableArrayDef.  E.g. in NumberLine.js:

```js
    // @public (read-only) {ObservableArrayDef<NumberLinePoint>} - array of points on this number line
```

Should be `{ObservableArrayDef.<NumberLinePoint>}`

**Comment by jbphet** [comment]
I used a regular expression to search through the code and find the offending declarations in both number-line-operations, number-line-integers, and number-line-common.  They have been corrected.  I also put the PSA on the agenda for the next dev meeting.

There are some in number-line-distance as well.  I'll bring them to @SaurabhTotey's attention.

Closing.
