### ISSUE TITLE
Incomplete type expressions for function

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#49]
Related to #35 code review.  From the CRC:

> - [ ] Type expressions for functions have a variety of possibilities, increasing in complexity depending on the case. In general note that {function} is not enough information.  Here are some better options: ...

This is violated in NumberLine.js, lines 33 & 43:

```js
33      // {function} - constraint for values that points can take on, integer values by default
        constrainPointValue: proposedValue => Utils.roundSymmetric( proposedValue ),
...
43    // @private {function}
    this.constrainPointValue = options.constrainPointValue;
```

`{function(value:number):number}` is probably what should be used here.

**Comment by jbphet** [comment]
I've improved the type expression based on the CRC recommendations.  Closing.
