### ISSUE TITLE
Violations of naming convention for Enumerations

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#50]
Related to #35 code review. 

PhET convention is for Enumeration types to typically have singular names.  This is what you've done with `PiggyBankDecoration`, `PageControlPosition`, `PointsOffScaleCondition`, and `LockToNumberLine`.  And this is what I see throughout PhET code, with some exceptions -- search for "= Enumeration.byKeys".  

`Operations` and `RelativePositions` violate this naming convention and should probably be renamed.

**Comment by jbphet** [comment]
renamed as suggested, closing
