### ISSUE TITLE
Differentiate between `Property` and "property".

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#51]
Related to #35 code review. From the CRC:

> - [ ] Differentiate between `Property` and "property" in comments. They are different things. `Property` is a type in AXON; property is any value associated with a JavaScript object. Often "field" can be used in exchange for "property" which can help with clarity. Search for "property" to identify violations.

number-line-common and number-line-operations have numerous violations.

**Comment by pixelzoom** [comment]
Fixed in the above commit.  Over to @jbphet for review.

**Comment by jbphet** [comment]
Changes look good, thanks.  Closing.
