### ISSUE TITLE
TODO comments

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#52]
Related to #35 code review. From the CRC:

> - [ ] Are there any TODO or FIXME or REVIEW comments in the code? They should be addressed or promoted to GitHub issues.

This one in NumberLineOperationNode.js needs an issue:

```
      // TODO: follow up with JO as to whether the need for adjustment is actually a bug
```

This one in NumericalExpressionAccordionBox.js presumably should be addressed before publishing:

    // TODO: The layout of these buttons is going through some churn.  Delete whatever isn't used when this gets finalized.  See https://github.com/phetsims/number-line-operations/issues/30.
```

**Comment by jbphet** [comment]
I've added an issue for the TODO associated with the arrow shape, and removed the other, which was related to some layout alternatives.  Closing.
