### ISSUE TITLE
factor out CurvedArrowNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#53]
Related to #35 code review. From the CRC:

> - [ ] Are the source files reasonable in size? Scrutinize large files with too many responsibilities - can responsibilities be broken into smaller delegates?

I usually inspect files that are > 500 lines, and there are 2 such files in this sim (output of `wc -l`):

     666 number-line-common/js/common/view/SpatializedNumberLineNode.js
     685 number-line-operations/js/common/view/NumberLineOperationNode.js

They are both well-documented and well-organized.   I wouldn't change anything with SpatializedNumberLineNode.js.   

For NumberLineOperationNode.js, I would definitely factor out a class whose responsibility is the curved arrow, something like `CurvedArrowNode`.  The current implementation has `this.curvedLineNode = new Path`, and the code to set that Path is throughout NumberLineOperationNode (not well-encapsualted).   I supsect that would significantly reduce the size of NumberLineOperationNode, and it's definitely a responsibility that could be delegated to another class.   If I wanted to reduce the size of NumberLineOperationNode.js, I might then consider moving `ArrowHeadNode` and `CurvedArrowNode` to their own .js files.  But I don't feel too strongly about that - having them as private classes serves the purpose of separating out responsibilitiies, and making NumberLineOperationNode more maintainable.

So... My recommendation is to factor out something like CurvedArrowNode.  Up to you whether to do this.

**Comment by jbphet** [comment]
I factored out a file called `OperationArrowNode` to improve the modularity.  This file and the `NumberLineOperationNode` from whence it came are both now less than 500 lines.  I could have gone a step further and made the curved arrow node more "pure" and not coupled to the operation and number line, but this seemed in many ways like it would make the code more complicated.  For now, what I've done here seems good, and I'll do more if I ever need to make the curved arrow into a more general component.  Closing.
