### ISSUE TITLE
Documentation style is distracting

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#54]
Related to #35 code review.  There's no CRC item for this, and PhET hasn't defined a convention. 

Much of the documentation in this sim (especially for methods) avoids using complete sentences, proper case, and punctution. This style might be the result of multiple developers having worked on this sim.  But I find it distracting and (to be blunt) a bit lazy.

PointController.js is a good example.  Here's the documentation for a few of its many methods, most of which use this style:

```js
141 *  clean up any linkages or other associations that could cause memory leaks

154 * returns whether this point controller is controlling one or more number line points

163 * associate this controller with a point on the number line

227 * remove all controlled points from the number line on which each one resides

237    * propose a new position to this point controller, may or may not actually update the position depending on whether
238   * a point on the number line is being controlled and how that point moves

320 * go to the specified position, either immediately or via an animation

416 * restore initial state
```

I agree that there's a place for using sentence fragments - they are especially useful (and appropriate) in documenting fields and params, or annotating "chunks" of code.  But if you have a sentence, why not make it look like a sentence?  And think of the reader - is this the documentation that you really want them to see?  If you were reading the JSdoc for a 3rd-party JS library, how would you feel about doc that looked like this, and how would it make you feel about that library? 

Using active tense for method documentation is also highly recommended. It's the standard for Java. For example, instead of this:

```diff
- * restore the initial state
+ * Restores the initial state.
```

So...  Probably nothing that you acutally need to do for this sim.  But consider for the next sim, or label for dev meeting if you think a broader discussion would be useful.

**Comment by pixelzoom** [comment]
Here's an example of a really nice comment header, in NumberLine.js. It starts by identifying the class ("NumberLine is"), uses complete sentences with punctuation, and communicatates useful information about its responsibilities and its overall design. 

```js
/**
 * NumberLine is a simple model of a number line.  It tracks points that are on the line, and those points can be added
 * and removed.  Since the line is one-dimensional, the points have only a single value.  This model is a somewhat
 * "pure" representation of a number line in the sense that it is not projected into space, nor is it limited in its
 * span.  Other subclasses add that functionality.
 *
 * @author John Blanco (PhET Interactive Simulations)
 * @author Chris Klusendorf (PhET Interactive Simulations)
 */
```

Here's an example that needs work. There's an attempt at capitalization, but no punctuation, abbreviated sentence structure ("Is passed" -> "It is passed").  And the overall information conveyed could use some polishing. 

```js
/**
 * Represents when a point controller should lock to a number line
 * Is passed in to point controllers as an option during construction
 *
 * @author Saurabh Totey
 */
```

**Comment by jbphet** [comment]
I think this is a fair point, and I've been making modifications to the comments as I go through.  I do think that this is in part a result of multiple people working on the code, but I've also been a bit unclear myself as to what the preferred style is.  I'm totally up for the idea of sentences with correct punctuation where needed.

I'll take a pass through some of the code and do what I can in a finite amount of time, and will endeavor to capitalize and punctuate sentences in future sims.

@SaurabhTotey - I'm assigning this to you to read through and then apply to number-line-distance and any number-line-common code that you've recently added.  Feel free to log a separate GitHub issue for tracking commits if you like.

@pixelzoom - One question.  One of your examples above looks like this:

```diff
- * restore the initial state
+ * Restores the initial state.
```

This seems to me like it went from an unpunctuated full sentence in the active voice to a punctuated sentence fragment, so I'm not quite clear on what you're suggesting in this particular example.  Could you please elaborate?

**Comment by jbphet** [comment]
I took a pass through number-line-operations and number-line-common where I used a regular expression to find a number of unpunctuated sentences that were used in methods and fixed them up.  Seems like an improvement.  I think I'll take a pass through number-line-integers before closing this.

**Comment by jbphet** [comment]
For future reference, here are some useful regular expressions for finding comments that start with a lower case character.  When used in IntelliJ or WebStorm, the case sensitivity switch in the search dialog needs to be turned on.

This one is for header comments (mostly methods and files):
```
/\*\*\n\s*\* [a-z]
```

This one is mostly for in-line comments:
```
^ \s*\/\/ [a-z]
```

**Comment by pixelzoom** [comment]
> I'm not quite clear on what you're suggesting in this particular example. Could you please elaborate? I mean, wouldn't "Restore the initial state." better match what you're describing?

yeah, you're right - "Return..." would be a complete sentence.  The more important point I was trying to make is that active voice is preferrable.   https://www.cs.cornell.edu/courses/JavaAndDS/JavaStyle.html is a pretty good summary:

> The Elements of Style, a famous little book on writing style by Cornell Professors W. Strunk, Jr., and E.B. White, contains several rules that are useful for programming as well as writing. Among them are:
> 
> Omit needless words.
> Use the active voice.

There's a "Java documentation style guide somewhere" that I can't seem to find right now that have more examples of "active voice", and I think that's where I got the preference for "Returns..." over "Return..."   But I don't feel strongly abou that, and I'm also OK with fragments that make sense.  If I can read it once, learn what I need to know, and not be mentally dragged into "comment editor" role, then mission accomplished.

**Comment by SaurabhTotey** [comment]
Yeah, I'm definitely a culprit for this too, so I'll update documentation as I come across it in NLD. Thanks for tagging me in this issue!

**Comment by jbphet** [comment]
I've done a bunch of mods to the comments, mostly focused on the comment that said "But if you have a sentence, why not make it look like a sentence?".  I did some other cleanup and modification of tenses.

I'm unassigning myself.  @SaurabhTotey - You should probably just open a separate issue in the NLD repo, reference this one, and then close this one.

**Comment by SaurabhTotey** [comment]
Alright, I went ahead and did that. I'll close this issue now.
