### ISSUE TITLE
Incorrect type expression for object literals

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#55]
Related to #35 code review. From the CRC:

> ii. When using an Object with specific properties, name them and their types like so:
* `@param {name:string, address:{street:string}, returnNode:function(number):Node, [shoeSize:number]} personalData // note that shoeSize is optional here`

In NumberLine.js:

```js
    // @private {Object{ initialValue, color}[]} - array of point specifications that describe what points should
    // exist on the number line when constructed and after a reset
    this.initialPointSpecs = options.initialPointSpecs;
```

`Object{...}` is bogus, and there's no type info for the fields. I'm guessing that this shiould be something like `{initialValue:number, color:Color}`.

**Comment by jbphet** [comment]
fixed, closing
