### ISSUE TITLE
Missing @override for dispose and reset

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#56]
Related to #35 code review.

There are 6 overrides of `dispose` in number-line-common and number-line-operations, search for "super.dispose".  They are all missing the `@override` annotaton, like this one in AbsoluteValueSpanNode.js:

```js
  /**
   * @public
   */
  dispose() {
    this.disposeAbsoluteValueSpanNode();
    super.dispose();
  }
```

**Comment by pixelzoom** [comment]
Also missing `@override` for reset in a couple of places. 

Fixed all of these in the above commits. Over to @jbphet for review.

**Comment by jbphet** [comment]
Changes look good, thanks @pixelzoom.  Closing.
