### ISSUE TITLE
NLCheckbox defines dispose as static

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#57]
Related to code review #35.

NLCheckbox defines `dispose` as static:

```js
  /**
   * @public
   * @override
   */
  static dispose() {
    assert && assert( false, 'NLCheckbox does not support dispose' );
  }
```

I doubt that the intent was to add a static `dispose` method, and the `static` keyword should likely be removed.

**Comment by jbphet** [comment]
Hmmm, not sure how that happened, but it is indeed incorrect.  The `static` keyword has been removed.  Closing.
