### ISSUE TITLE
Missing type expressions for empty arrays

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#59]
Related to #35 code review.

There are quite a few arrays that are initialized to `[]` where they are defined, with no type expression to describe what they contain.  I'll fix the obvious ones, and will note the ones that I can't figure out here.

OperationTrackingNumberLine.js, where the type expression `{number}` is also incorrect:

```js
      // {number} - options used for each of the tracked operations, can either be an empty array or a number that
      // matches the number of tracked operations
      operationOptionsArray: []
```

NumericalExpressionAccordionBox.js:

```js
        // make a list of all the values and operations
        const valuesAndOperations = [];
```

**Comment by pixelzoom** [comment]
I took care of several in the above commits. Assigning to @jbphet to review, and to address the 2 that are identified in https://github.com/phetsims/number-line-operations/issues/59#issue-778333702.

**Comment by jbphet** [comment]
The changes look good, and I've added type descriptions for the others that were mentioned above.

One question: `valuesAndOperations` is a `const` that is declared in an update function, and is not a part of the API or even visible at all on the prototype.  Is it PhET's policy that even cases like this should have a type declaration for the array?

**Comment by pixelzoom** [comment]
Whenever you define an empty array, it's a good practice to note what type of elements will be in that array. Otherwise the reviewer/maintainer has to read through the code, and try to figure out what type (or types!) of elements are added later.  

`valuesAndOperations` is actually a create example. Here's the relevant code in NumericalExpressionAccordionBox.js:

```js
        // {Array.<number|OperationType>} - a list of all the values and operations needed to create the expression
        const valuesAndOperations = [];

        // add the starting value
        valuesAndOperations.push( numberLine.startingValueProperty.value );

        // go through the operations, adding the values and operation types to the list
        activeOperations.forEach( ( operation, index ) => {

          // the first operation is a special case - it's not included if the starting value was left off
          if ( index > 0 || valuesAndOperations.length > 0 ) {
            valuesAndOperations.push( operation.operationTypeProperty.value );
          }
          valuesAndOperations.push( operation.amountProperty.value );
        } );
```

I'm going to ignore the type expression that you added, and describe what I had to go through to determine the type of `valuesAndOperations`. 

There are `push` calls involving 3 different Property values, so potentially 3 different element types.

First, track down `numberLine.startingValueProperty` and determine it's Property type.  That requires determining the type of param `numberLine`, then navigating to `OperationTrackingNumberLine`, then finding the type of its `startingValueProperty`, which I find to be `NumberProperty`.  So now I know that `valuesAndOperations` has elements of type `{number}`.

I should have guessed that the array contains more than one element type, but let's suppose that I haven't had my coffee yet.  If I stopped here and assumed `{Array.<number>}`, I'd be wrong. 

So next I need to determine the type of `operation.operationTypeProperty`.  `operation` is a member of `activeOperations`, which comes from `numberLine.getActiveOperations()`, which returns `{NumberLineOperations[]}`.  And surprise! NumberLineOperations.js does not exist.  So off on a tangent I go -- created #85, fixed that problem -- and I've finally determined that `operationTypeProperty` is `{Property.<OperationType>}`.   So now I know that `valuesAndOperations` has elements of type `{number|OperationType}`.

Can I stop there? Not safely -- I still need to investigate `operation.amountProperty`.  From the previous step, I know that `operation` is `{OperationType}`, so I determine that `amountProperty` has value of type `number`.   So after a quick check that I didn't miss any `push` calls, I'm now reasonably certain that `valuesAndOperations` has elements of type `{number|OperationType}`.

All of the above took me > 5 minutes. And unless I added the type expression, the next person gets to repeat the same exercise.  This could be avoided by including a type expression for `valuesAndOperations` at  its call site, as you've added:

```js
        // {Array.<number|OperationType} - a list of all the values and operations needed to create the expression
        const valuesAndOperations = [];
```

Make sense?

**Comment by jbphet** [comment]
Sounds good.  For the most part, I had only been thinking about adding type expressions to externally visible portions of the object, but from here on I'll consider using then internally where they're helpful.  Thanks for the thorough explanation.  Closing.
