### ISSUE TITLE
Artwork or design needed for screen icons

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-operations#6]
We're getting close to the point where we will need to replace the current placeholders for the home screen and nav bar icons with the "real deal".  @amanda-phet - can you provide designs and, if they don't lend themselves to programmatic generation, artwork that can be used for this?

**Comment by amanda-phet** [comment]
@ariel-phet any thoughts?

![image](https://user-images.githubusercontent.com/7852916/89441926-272b9080-d70b-11ea-90ec-3d3ed49a59d9.png)

**Comment by amanda-phet** [comment]
I think the Generic icon needs work. I'll try making it all bigger and bolder.

**Comment by amanda-phet** [comment]
![image](https://user-images.githubusercontent.com/7852916/89442084-6e198600-d70b-11ea-8173-9295ff374408.png)

**Comment by ariel-phet** [comment]
@amanda-phet I think those look great!

**Comment by amanda-phet** [comment]
![NLO-screen-icons-01](https://user-images.githubusercontent.com/7852916/89469001-d7ae8a00-d735-11ea-9823-8d1805956a1c.png)
![NLO-screen-icons-02](https://user-images.githubusercontent.com/7852916/89469003-d8472080-d735-11ea-87e7-32eab5db6766.png)
![NLO-screen-icons-03](https://user-images.githubusercontent.com/7852916/89469004-d8472080-d735-11ea-8f84-0c77705aef97.png)
![NLO-screen-icons-04](https://user-images.githubusercontent.com/7852916/89469005-d8dfb700-d735-11ea-8fd7-5b0a85887919.png)

**Comment by amanda-phet** [comment]
I think the icons are working, and didn't pose issues in interviews. Closing!
