### ISSUE TITLE
Allow users the choice to have two different axes for number lines?

### ISSUE THREAD

**Issue by brooklynlash** [phetsims/number-line-operations#62]
Not sure if this is necessary or not but just an idea, for the "Generic" screen there is a choice to add a number line, but both axes have the same distance. Should there be the option to have two different size axes, i.e. one being from -10 to 10 and one being from -100 to 100?
This is for https://github.com/phetsims/QA/issues/593

![numba](https://user-images.githubusercontent.com/72031637/103100034-a855c800-45c5-11eb-8785-c0d7b0cd41da.PNG)

**Comment by amanda-phet** [comment]
I do like that idea... but the main purpose of two learning goals is to compare two different numerical expressions, and I'm not sure you need two scales to do that. I also am unsure about where we'd put that combobox, since it was already a headache fitting all of this in the screen!

**Comment by amanda-phet** [comment]
Discussed 1/7/21 and there is potential to cause confusion if the scales are different. So we'll leave this as-is. Thanks @brooklynlash !
