### ISSUE TITLE
Approach to removing observers is poorly documented

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#63]
Related to #35 code review. From the CRC:

> -[ ]  Are there leaks due to registering observers or listeners? The following guidelines should be followed unless documentation (in-line or in implementation-notes.md) describes why following them is not necessary.
...

There is nothing in implementation-notes.md that describes the overall approach to observers (aka listeners) -- I was looking for something like "unless otherwise documented, all observers need to be removed".    I inspected many call sites for `link`, `addListener`, etc. and there is nothing at the call sites that indicates whether (and why) an observer needs to be (or doesn't need to be) removed.   In short, I could find no useful informtion related to this important CRC item.  It's great that there doesn't appear to be any memory leak (see #17) because I'd hate to have to figure out which observers do and do not need to be removed. 

I highly recommend:

(1) Adding something to implementation-notes.md that describes how you've generally handled observers, and
(2) Add comments in the code wherever there are exceptions to that general approach.    

For example, if your general approach is "unless otherwise documented, all observers need to be removed", then an observer that doesn't need to be removed would be documented like this:

```js
// unlink is not needed, exists for the lifetime of the sim.
someProperty.link( someValue => { ... } );
```

**Comment by jbphet** [comment]
I've added a section on "Memory Management" to the documentation, and also added notes to the code comments for most if not all `link` and `addListener` calls.  I think this should cover the concern that was expressed.  Closing.
