### ISSUE TITLE
dispose requirements are poorly documented

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#64]
Related to #35 code review. From the CRC:

> - [ ] Do all types that require a `dispose` function have one? This should expose a public dispose function that calls this.disposeMyType(), where disposeMyType is a private function declared in the constructor. MyType should exactly match the filename.

I have no idea if this item is satisified, because there's no documention in implementation-notes.md that identifies how to know this -- e.g. which objects are dynamic and which objects exist for the lifetime of the sim, or which objects implement dispose and why, etc.

It's also difficult to conclude that the objects that require disposal are the ones that implement `dispose`. NumberLinePoint for example, which I would have guessed is dynamic, has a `dispose` method that is unlikely to have been tested and will certainly fail, see https://github.com/phetsims/number-line-operations/issues/58. 

So... While it's fresh in your mind, you might want to include some info on this topic in implementation-notes.md.   Identify which classes are dynamic and require disposal.  Or put that info in the .js files, if you prefer, and note that in mplementation-notes.md.

In future sims, you might also consider something like this, described in natural-selection implementation-notes.md:

> **Memory Management**
> * **dispose**: Sim-specific classes whose instances exist for the lifetime of the sim are not intended to be disposed, and their `dispose` implementation looks like this:
> 
> 
> ```js
> /**
>  * @public
>  * @override
> */
>  dispose() {
>     assert && assert( false, 'dispose is not supported, exists for the lifetime of the sim' );
>     super.dispose();
>   }
> ```

**Comment by pixelzoom** [comment]
This CRC item fails for the same reason:

> - [ ] For each common-code component (sun, scenery-phet, vegas, …) that opaquely registers observers or listeners, is there a call to that component’s `dispose` function, or is it obvious why it isn't necessary, or is there documentation about why `dispose` isn't called?  An example of why no call to `dispose` is needed is if the component is used in a `ScreenView` that would never be removed from the scene graph.

**Comment by jbphet** [comment]
I've enhanced the `implementation-notes.md` document as well as a number of code comments to partially address this concern.  I didn't add the dispose function that asserts, but will consider doing so in future development.  Closing.
