### ISSUE TITLE
options are not propagated to the superclass

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#65]
Related to #35 code review.

When I see a subclass that has an `options` parameter (especially a Node subclass), there's an expectation that `options` will be propagated to the superclass via `super` or `mutate`.     It's the reason that this default documentation is generally sufficient:

```
@param {Object} [options]
```

The problem with not meeting that expectation is that I'll only find out that I can't provide superclass options if I either read the code or (more likely) find out the hard way and then have to read the code.

These subclasses don't propagate options to the superclass, and it's not clear whether that's by design or unintentional:

* PointNode
* SpatializedNumberLineNode
* ControllableOperationNumberLineNode
* InteractiveNumberLineView

So 2 things...

(1) For the above classes, confirm that `options` are not propagated to super _by design_, and not due to a programming oversight.

(2) In cases where `options` are not propagated to super, indicate that in the JSdoc, e.g.:

```
 * @param {Object} [options] - specific to this class, not propagated to super
```

**Comment by jbphet** [comment]
Another good observation.  I'd never really thought about the expectation that options would be passed to the superclass, but it makes sense.  I've added the suggested documentation (or variations thereof) in the cases that are listed above, and will try to remember to add similar docs when this situation comes up in the future.  Closing.
