### ISSUE TITLE
Document how SVG strings were created

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#67]
Related to #35 code review.  

piggyBankShapes.js contains `PIGGY_BANK_SVG_STRING`, which is an SVG string.  Where this SVG came from (which asset, etc.) is undocumented.   I'm guessing it's piggy-bank-outline.svg.  But then the next question is where did that come from?  It's undocumented, but I'm guessing it's piggy-bank.ai.  ...

So if I had to change this SVG, there would be some guessing and trial-and-error involved. Why not document exactly how you got from piggy-bank.ai to `PIGGY_BANK_SVG_STRING`?

**Comment by pixelzoom** [comment]
Ditto for `BAG_OUTLINE_SVG_STRING` in FillableBagNode.js.

**Comment by jbphet** [comment]
There was documentation about the piggy banks in number-line-integers, but I had neglected to move it when I moved the piggy bank classes into number-line-common.  I've moved it, and also added information about the SVG strings for `FillableBagNode`.  I think that should address this issue, closing.
