### ISSUE TITLE
Better documented needed for logPointOperationChain

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#68]
Related to #35 code review.

`OperationTrackingNumberLine` has method `logPointOperationChain`, documented like this:

```js
  /**
   * Log to the console the current point-operation chain.  This is used for debugging.
   * @public
   */
```

`logPointOperationChain` is currently not called anywhere in the code. I have no idea how to use this, or when it would be useful.  Is it supposed to be temporaritly added to the code when needed? Called from the console on a some global instance?... Consider providing more documentation. Also consider using `phet.log` instead of `console.log`.

**Comment by jbphet** [comment]
It was a convenience method for debug, but since it seemed to be causing some confusion and could be replicated fairly easily if it were ever to be needed again, I decided to remove it.  Closing.
