### ISSUE TITLE
Duplicated code

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#69]
Related to #35 code review.  From the CRC:

>  -[ ] Are any significant chunks of code duplicated? ...

I used WebStorm menu item "Code > Locate Duplicates" to identify duplicate code. Here are the duplicates that seem significant.  I'll leave it to @jbphet to decide which ones are worth addressing.

- [x] Duplicated 2x In SpatializedNumberLineNode.js, see lines 159 and 167.

```js
      const pointsSortedByValue = _.sortBy( numberLine.residentPoints, point => {
        return Math.abs( point.valueProperty.value );
      } );
```

- [x] Duplicated 2x in AbsoluteValueSpanNode.js

```js
() => {
      updateSpanShape();
      updateEquation();
    }
```

- [x] Duplicated 2x in PointController.js:

```js
if (  this.lockToNumberLine === LockToNumberLine.ALWAYS || this.lockToNumberLine === LockToNumberLine.WHEN_CLOSE ) {
```

- [x] Duplicated in NLOChipsScreenView.js and NLONetWorthScreenView.js:

```js
    const resetAllButton = new ResetAllButton( {
      listener: () => {
        this.interruptSubtreeInput(); // cancel interactions that may be in progress
        model.reset();
      },
      right: this.layoutBounds.maxX - NLCConstants.SCREEN_VIEW_X_MARGIN,
      bottom: this.layoutBounds.maxY - NLCConstants.SCREEN_VIEW_Y_MARGIN,
      tandem: tandem.createTandem( 'resetAllButton' )
    } );
```

- [x] Duplicated 4x (2x each) in NLOChipsModel and NLONetWorthModel:

```js
            this.storageBoxes.forEach( storageBox => {
              if ( storageBox.holdsItem( chip ) ) {
                storageBox.returnItem( chip, true );
              }
            } );
```

- [x] Duplicated in NLOChipsScreenView.js and NLSNetWorthScreenView.js:

```js
    const checkboxes = [
      new NLCheckbox(
        numberLineOperationsStrings.operationLabels,
        model.numberLine.showOperationLabelsProperty
      ),
      new NLCheckbox(
        numberLineOperationsStrings.operationDescription,
        model.numberLine.showOperationDescriptionsProperty
      ),
      new NLCheckbox(
        numberLineOperationsStrings.tickMarks,
        model.numberLine.showTickMarksProperty
      )
    ];
```

- [x] Duplicated 4x, in every ScreenView subclass (NLOChipsScreenView, NLOGenericScreenView, NLONetWorthScreenView, NLOOperationsScreenView)

```js
    const checkboxGroup = new VBox( {
      children: checkboxes,
      spacing: NLOConstants.CHECKBOX_SPACING,
      align: 'left',
      left: this.layoutBounds.minX + NLCConstants.SCREEN_VIEW_X_MARGIN,
      top: this.layoutBounds.minY + NLCConstants.SCREEN_VIEW_Y_MARGIN
    } );
```

- [x] Duplicated 2x in DynamicOperationDescription.js

```js
    this.fadeAnimation.finishEmitter.addListener( () => {
      this.fadeAnimation = null;
    } );
```

- [x] Duplicated 2x in BalanceSheetItemNode.js

```js
      StringUtils.fillIn( numberLineOperationsStrings.monetaryValuePattern, {
        sign: '', // don't show minus sign for debts, since that would be a sort of double negative
        currencyUnits: numberLineOperationsStrings.currencyUnits,
        value: Math.abs( balanceSheetItem.value )
      } ),
```

- [x] Duplicated 3x in SingleDualNumberLineSelector.js

```js
new ArrowNode( -ARROW_ICON_LENGTH / 2, 0, ARROW_ICON_LENGTH / 2, 0, ARROW_ICON_OPTIONS )
```

- [x] Duplicated in NLOChipsModel.js and NLONetWorthModel.js

```js
  step() {
    this.numberLine.step();
  }
```

- [x] Duplicated 2x in NLOGenericModel.js and NLOOperationsModel.js.  Should these colors be factored out?

```js
        pointColorList: [ new Color( '#0000C4' ), new Color( '#4069FF' ), new Color( '#64A3FF' ) ]
```

**Comment by jbphet** [comment]
I've gone through the list of items listed above and, in most cases, done some reduction of the duplicated code.  There was one case that had already been addressed, and a few where I thought it was either better left as is or more work than could be reasonably justified to change.  Closing.
