### ISSUE TITLE
ControllableOperationNumberLineNode reset method is buggy

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#71]
Related to #35 code review.  

While identifying duplicate code in #69, I noticed this `reset` method that is duplicated in NLOGenericScreenView.js: and ControllableOperationNumberLineNode.js: 

```js
  reset() {
    this.operationEntryCarousel.reset();
  }
```

This looks like a bug to me, because `ControllableOperationNumberLineNode extends Node` and has no `this.operationEntryCarousel` field.  I'm guessing that ControllableOperationNumberLineNode `reset` is never called, and can be removed.

**Comment by jbphet** [comment]
Yep, I think it was probably a cut-and-paste error.  The method has been removed.  Closing.
