### ISSUE TITLE
Get rid of only one addition

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-operations#72]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/593. Mostly a suggestion for the Operations and Generic screen. Should there be individual erase buttons/options for the addition/subtractions? Basically, you may want to remove a second addition but not remove the first. You can set the second addition you added to 0, which leave behind an odd arrow that may be distracting. Or, you can erase both and recreate just the first addition. However, I can't find a way to erase just one of the additions. This doesn't lead to any bugs that I've found so far, but it can feel clunky and inefficient.

**Visuals**
![justgetridofone](https://user-images.githubusercontent.com/41024075/103590708-c667d600-4eab-11eb-8cf0-3efff868e4b2.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Operations‬
URL: https://phet-dev.colorado.edu/html/number-line-operations/1.0.0-dev.12/phet/number-line-operations_all_phet.html
Version: 1.0.0-dev.12 2020-12-23 23:50:10 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Language: en-US
Window: 1280x658
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by amanda-phet** [comment]
We removed that option after interviews proved it to be an unproductive option. Since it's just two total, it didn't seem like a huge deal to have to redo it if erased.
