### ISSUE TITLE
Inappropriate use of type-specific Properties in type expressions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#73]
Related to #35 code review.  From the CRC:

> - [ ]  Prefer the most basic/restrictive type expression when defining APIs. For example, if a client only needs to know that a parameter is `{Node}`, don’t describe the parameter as `{Rectangle}`.

This is violated in the case of type-specific Properties. Type-specific Properties are inappropriately used in many type expressions. For example, in InitialNetWorthAccordionBox.js:

```
* @param {NumberProperty} initialNetWorthProperty
```

There is nothing in the implementation of `InitialNetWorthAccordionBox`, its superclass, or its subcomponents, that requires a `NumberProperty`.  The correct type expression is `{Property.<number>}`.

There are many other misuses of `{NumberProperty}` and `{BooleanProperty}`.  Probably not worth fixing them at this point, but keep in mind for future development.

**Comment by jbphet** [comment]
Noted, thanks for pointing this out.  I basically thought of the two forms as equivalent, but it is indeed true that the type-specific classes have additional features.  I'll keep this in mind in future development.
