### ISSUE TITLE
new Range( -1000, 1000 ) is duplicated 4x

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#74]
Related to #35 code review.  From the CRC:

>  - [ ] Are there any constants that are duplicated in multiple files that should be factored out into a {{REPO}}Constants.js file?

This range is duplicated 4 times:

```
new Range( -1000, 1000 )
```

Should it be factored out into NLOConstants.js?

**Comment by jbphet** [comment]
Due to work on #75, there are now only two places where this range is duplicated.  These two are more coincidental than truly shared values, and may change independently in the future, so I don't think it makes sense to consolidate them.  Closing.

**Comment by pixelzoom** [comment]
> ... These two are more coincidental than truly shared values, and may change independently in the future ...

You might want add a comment in the code, so that someone doesn't combine them in the future.

**Comment by jbphet** [comment]
> You might want add a comment in the code, so that someone doesn't combine them in the future.

I started adding such a comment, and ended up consolidating the constants after all.  They are both net worth values, so maybe it was more of an intentional design element than I thought.  They can always be divided up in the future if needed.
