### ISSUE TITLE
initialNetWorthProperty range should be defined in the model

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-operations#75]
Related to #35 (code review) and #74 (new Range( -1000, 1000 ) is  duplicated) ...

In InitialNetWorthAccordionBox.js:

```js
    const initialNetWorthPicker = new NumberPicker(
      initialNetWorthProperty,
      new Property( new Range( -1000, 1000 ) ),
```

`new Range( -1000, 1000 )` seems inappropriate here.  `initialNetWorthProperty` is defined in the model, and is a NumberProperty.  Why is the range not associated with that model Property, so that the above code is:

```js
    const initialNetWorthPicker = new NumberPicker(
      initialNetWorthProperty,
      initialNetWorthProperty.rangeProperty,
```

**Comment by pixelzoom** [comment]
Same concern about this range in NLOOperationsScreenView.js.  Why is this range not associated with the model, or a model NumberProperty?

```js
    const commonEntryControlOptions = {
      numberPickerRange: new Range( -1000, 1000 ),
```

**Comment by jbphet** [comment]
Good point.  There is actually an appropriate range property in the number line instance(s) in the model: `displayedRangeProperty`.  I've changed the code to use this, and done some related refactoring as well.  This also helps with #74.

I think this addresses the problem.  Closing.
