### ISSUE TITLE
Erase button sets operations to 0

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-operations#76]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/593
This happens on both Operations and Generic screen. When you use the erase button on a number line, it sets the operations for that line (whether they were in use or not) to 0. This seems odd to me. It seems like it should either remove the points but keep the values the same, or if it has to reset them, reset them to the default value when the page is reloaded/refresh all is used.
**Steps to reproduce**
1. Pick a number line on either Operations or Generic
2. Add one of the operations to the line with a non-zero number
3. Make sure the second operation is non-zero, but don't add it.
4. Hit the erase button for that line
5. Observe both operations

**Visuals**
![erasesettozero](https://user-images.githubusercontent.com/41024075/103683038-eb5d5700-4f46-11eb-87b3-a128c14424cd.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Operations‬
URL: https://phet-dev.colorado.edu/html/number-line-operations/1.0.0-dev.12/phet/number-line-operations_all_phet.html
Version: 1.0.0-dev.12 2020-12-23 23:50:10 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Language: en-US
Window: 1280x658
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by amanda-phet** [comment]
This is intentional. The picker starts at 100 since that is more "useful" than 0, but we think 0 makes more sense as a blank slate after erasing.
