### ISSUE TITLE
Add slight animation delay when two things are dropped at once

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-operations#77]
**Test device**
Dell (With touch screen)
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/593. Mostly only seen with multitouch. Less of a bug and more of a suggestion.
When two objects (coins or items in the first two screens) are dropped into their bags at the same time with multitouch, only one visible animation plays. I'm wondering if it would be useful to play the first animation for a second or so before moving on to the next animation. This might maintain continuity better. However, if you start pushing this, I can see this solution becoming a problem itself, so feel free to ignore this and close if it seems like a bad idea.

**Visuals**
![delayanimationiffast](https://user-images.githubusercontent.com/41024075/103693690-ed2f1680-4f56-11eb-92e2-bc5d79630b97.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Operations‬
URL: https://phet-dev.colorado.edu/html/number-line-operations/1.0.0-dev.12/phet/number-line-operations_all_phet.html
Version: 1.0.0-dev.12 2020-12-23 23:50:10 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Language: en-US
Window: 1280x658
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by amanda-phet** [comment]
My guess is it's nearly impossible to actually drop both at the same time, so this is behaving as desired and showing only the most recent. I'm not sure it's worthwhile (or feasible) to come up with a solution for the situation where they actually are dropped at the same time (or nearly the same time).

**Comment by jbphet** [comment]
If @amanda-phet doesn't think it's worthwhile, I'm okay to close.  These isn't an obvious fix that I can think of off the bat.
