### ISSUE TITLE
Screenshots take longer on last two screens

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-operations#78]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/593. 
Taking a screenshot with the PhET Menu on the Chips and Net Worth screens seems almost instant. On the Operations screen it is slower, and on the Generic screen it takes several seconds. This is very noticeable and everything freezes while it is working. It is very consistent on those screens and only those screens, so it seems to be an issue with the sim rather than the device or randomness, but I'll do more testing after posting this issue.

**Visuals**
![genericscreenshots](https://user-images.githubusercontent.com/41024075/103695922-b3600f00-4f5a-11eb-8606-8ebce58d5d9b.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Operations‬
URL: https://phet-dev.colorado.edu/html/number-line-operations/1.0.0-dev.12/phet/number-line-operations_all_phet.html
Version: 1.0.0-dev.12 2020-12-23 23:50:10 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Language: en-US
Window: 1280x658
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
In addition, I didn't seem to see anything wrong with the actual resulting screenshots.

**Comment by KatieWoe** [comment]
This seems to mostly be a chrome issue. Happened on Mac 10.15 Chrome about the same. Win 10 Firefox barely saw it, and Mac Safari had it a bit, but less than in Chrome.

**Comment by kathy-phet** [comment]
https://github.com/phetsims/scenery/issues/1139

**Comment by jbphet** [comment]
This problem is due to an issue in common code that is being tracked in https://github.com/phetsims/scenery/issues/1139.

Unassigning for now, and will make sure the fix is integrated and tested once it becomes available.

**Comment by samreid** [comment]
@jonathanolson fixed https://github.com/phetsims/scenery/issues/1139 and it has been reviewed and closed.

**Comment by jbphet** [comment]
@KatieWoe - Since you're the one who originally reported this issue, can you please test on master and verify that it's fixed?

**Comment by KatieWoe** [comment]
Looks much better on master

**Comment by jbphet** [comment]
Cool.  I'm mark this as fixed but will leave open and we can double check on the next RC.

**Comment by KatieWoe** [comment]
This seems fixed in rc.1. Will reopen if something comes up.

**Comment by KatieWoe** [comment]
On slower devices (such as Lovelace with ChromeOS) it seems like there might still be a bit of a delay, but it is much better.

**Comment by jbphet** [comment]
@kathy-phet and I reviewed this and decided that it is not blocking to the publication of this sim.

@KatieWoe - @kathy-phet suggested that you make some measurements of this problem versus published sims and log a common code issue if you think it is warranted or close this if not.

**Comment by KatieWoe** [comment]
Closing for now. Will reopen if I see a bad instance
