### ISSUE TITLE
Operation Labels can make grabbing number controls difficult

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-operations#79]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/593.
When the Operation Labels on Operations and Generic screens are bellow the number line and the points are close together, the label can cover the draggable points, making it difficult to move them. This can also occur with the Operations Description on the Operations screen, but it is generally shorter so it happens less.
This may not need addressing as the spinners can still be used, the labels can be turned off, and there is still a (very small) area that is still grabbable. But if it is an easy fix, it might be worth it.
**Steps to reproduce**
1. Go to the Operations screen
2. Go to the second operation and add 100, the arrow and label should be bellow the line
3. Try to grab either number point

**Visuals**
![orbshardtograb](https://user-images.githubusercontent.com/41024075/103700421-a692e980-4f61-11eb-8058-d1ed7c61a396.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Operations‬
URL: https://phet-dev.colorado.edu/html/number-line-operations/1.0.0-dev.12/phet/number-line-operations_all_phet.html
Version: 1.0.0-dev.12 2020-12-23 23:50:10 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Language: en-US
Window: 1280x658
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by amanda-phet** [comment]
Yup I noticed this too! I think you used to be able to grab those controllers even with the label occluding them, so I'm not sure if this is a pointerAreas thing or what, but the label shouldn't be occluding the pointer area.

**Comment by jbphet** [comment]
Setting `pickable: false` seems to resolve this issue.

**Comment by KatieWoe** [comment]
Looks good in dev.13. Closing
