### ISSUE TITLE
Should there be a slight delay of the operation description appearing when point is first added?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-operations#81]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/593. This may be difficult to implement or cause other problems so feel free to close.
When adjusting a point before it has been added to the number line, the operation description is displayed near the top of the screen. When the point is added that text falls. The actual operation description label appears immediately as the point appears. The animation looks a bit like the the falling text should become the new label but the label is already there. It looks like the label should be delayed until the text finishes falling. However, there are potential problems with this, so it may not be worth addressing.

**Visuals**
![labeladdedfalling](https://user-images.githubusercontent.com/41024075/103801909-9a636680-500b-11eb-88db-6d4ffacb51ef.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Operations‬
URL: https://phet-dev.colorado.edu/html/number-line-operations/1.0.0-dev.12/phet/number-line-operations_all_phet.html
Version: 1.0.0-dev.12 2020-12-23 23:50:10 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Language: en-US
Window: 1280x658
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by amanda-phet** [comment]
Let's discuss this tomorrow!

**Comment by amanda-phet** [comment]
@jbphet is going to try delaying the animation on the number line (perhaps have it fade in as the description is fading out).

**Comment by jbphet** [comment]
I've implemented the basic behavior.  The design team should review this at our next meeting and see what the think.  I'm thinking we should consider having the operation go all the way to the number line, and/or some other potential adjustments.

**Comment by jbphet** [comment]
Reviewed and approved in design meeting, closing.
