### ISSUE TITLE
Create Net Worth screen icon without '$'

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-operations#84]

**Comment by amanda-phet** [comment]
Asset is updated and new icon is uploaded. Over to @jbphet to reprocess the image and add the string for currency. We want to try to match the font used on the Net Worth screen right on the pig.

**Comment by jbphet** [comment]
This is integrated and works well.  I had to do some experimentation to find a good combination of font and scaling amount.  I'm going to leave it open and have QA verify it on multiple platforms to make sure that it looks good on all of them.

Here are some screenshots using different currency symbols:

![image](https://user-images.githubusercontent.com/3082831/105779414-913f2880-5f2b-11eb-944b-ba1fe454f8cb.png)

![image](https://user-images.githubusercontent.com/3082831/105779350-605ef380-5f2b-11eb-9664-24d9f5fdc45c.png)

![image](https://user-images.githubusercontent.com/3082831/105779390-7ff61c00-5f2b-11eb-9097-a80ef7460177.png)

**Comment by amanda-phet** [comment]
The currency symbol looks great to me! 

Something funny about the icon though- there is an interior border. Did I do something funny when I exported it? Or are you scaling the icon in some way?

**Comment by jbphet** [comment]
@amanda-phet - Sorry, I appear to have missed this before going to RC.  It can still be fixed through, but we need to be clear on what the problem is.  Can you describe what you mean when you say "there is an interior border"?  Maybe mark up one of the images above or do a screen capture of your own?

**Comment by amanda-phet** [comment]
I see it in your screenshots above as well as on master when I reviewed the icons. 

I'm trying to indicate the rectangle here by just highlighting the corners of it. The interior is purple, and the exterior is white.

![image](https://user-images.githubusercontent.com/7852916/106037923-894ec800-6094-11eb-9b36-f5aeaef36d31.png)

**Comment by jbphet** [comment]
Ah, I see what you're referring to now.  I investigated, and it was related to the options that were being provided to the `ScreenIcon` class.  I've fixed them up and it looks better.  I've also propagated the change to the release branch, and will have this verified in the next RC.

**Comment by KatieWoe** [comment]
Looks good in rc.2. Will reopen if something comes up.
