### ISSUE TITLE
Alignment of ring and value looks off (Net Worth screen)

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-operations#86]
Discussed in 1/14/21 design meeting. 

While the rule might be consistent between all of the objects, the ring is the only one that doesn't seem to be centered with the other objects, and the value of which is also not aligned with the other values in the list. 

<img width="555" alt="image" src="https://user-images.githubusercontent.com/7852916/105200854-7de02780-5afd-11eb-80ee-c27f9d90853c.png">

**Comment by jbphet** [comment]
I added a transparent background for the in-bag icons to improve the alignment.  It works well, but changes the sizes of some of the other icons, the most noticeable being the credit cards.  I reviewed the change in appearance with @amanda-phet, and she's fine with it.  I'm going to mark this as fixed and will have QA verify it in the next release.

**Comment by KatieWoe** [comment]
Looks good in rc.1
