### ISSUE TITLE
Double plus sign bug?

### ISSUE THREAD

**Issue by zepumph** [phetsims/number-line-operations#88]
While @jessegreenberg and I did some testing in this sim to confirm fixes for https://github.com/phetsims/scenery/issues/1137, we found a potential bug. ![image](https://user-images.githubusercontent.com/6856943/105769600-858f3a00-5f0a-11eb-9fa9-9b651b0e8391.png)

In multiple places on the generic screen, it seems like there are blank numbers in between two "plus" signs, and only a number at the end. It kinda looks like it should be `_ + _ + 6` instead of `++6`. Is this a bug? I wasn't too sure.

**Comment by amanda-phet** [comment]
`++6` is intentional. In this case, the user is adding a positive 6. It is unconventional, which is why the statement reflects the real convention for writing an expression, but when someone switches the operation and/or sign of the operand, we want them to see what that means on the number line.
