### ISSUE TITLE
Pointer bug for hidden accordion box title

### ISSUE THREAD

**Issue by zepumph** [phetsims/number-line-operations#89]
While @jessegreenberg and I did some testing in this sim to confirm fixes for https://github.com/phetsims/scenery/issues/1137, we found a potential bug. I think this is common code, but I'll make it here because there is an easy test case and way to reproduce:

General issue: When an accordion box is open, but the title bar is hidden, the invisible, content-less titlebar still changes the cursor to be a pointer, even though it isn't interactive.

Steps to reproduce (there are many ways, but here is one):

1. Chips screen
2. Close the "total" accordion box
3. Notice that the whole bar has a pointer for the cursor.
4. Open it, and notice that where the "Total" text Node isn't on top (to either side of it), the title bar still has the pointer cursor.

@jbphet, what do you think about this? Does it block your RC?

**Comment by jbphet** [comment]
I'm going to make a call and say no, this does not block the release.  I'll leave it open and will consider fixing in a maintenance release once this behavior is fixed.

**Comment by jbphet** [comment]
This was fixed by a recent commit to common code, closing.
