### ISSUE TITLE
ComboBox does not consistently dismiss when clicking outside of it

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-operations#90]
This problem was brought up on Slack and is present in https://phet-dev.colorado.edu/html/number-line-operations/1.0.0-rc.1/phet/number-line-operations_en_phet.html.  To duplicate:
- Go to the "Generic" screen
- Open the combo box
- click outside of the box

This sequence may have to be repeated a few times - sometimes it works, sometimes it doesn't.

**Comment by jbphet** [comment]
The parent issue for this is https://github.com/phetsims/sun/issues/679#issuecomment-767840988, and the fix is committed in https://github.com/phetsims/sun/commit/03187fbb29ec42fa8851b06898a202502e0008f4.

**Comment by KatieWoe** [comment]
Linking to https://github.com/phetsims/QA/issues/600 so other testers are aware

**Comment by KatieWoe** [comment]
Seems fixed in rc.2
