### ISSUE TITLE
Mismatched layering of points

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-operations#91]
**Device**
iPad 6th Gen
**OS**
iPadOS 14.4
**Browser**
Safari
**Problem Description**
For https://github.com/phetsims/QA/issues/600. The layering of a point on the numberline and the draggable point bellow it may not be the same. This seems to occur when adjusting a point using the number spinners.
**Steps to Reproduce:**
1. Go to the last screen and add a point
2. Drag the operation point over starting point. Observe proper layering
3. Drag operation point off starting point. Do not touch starting point
4. Use number spinner to move operation point over starting point. Observe proper layering
5. Drag operation point off starting point. Drag starting point around. Do not touch operation point.
6. Use spinner to move operation point over starting point. Observe mismatched layering

**Visuals**

https://user-images.githubusercontent.com/41024075/106067746-8b2c8180-60bc-11eb-90e8-aa9481567e07.MP4

**Comment by brooklynlash** [comment]
Replicated on Win10 Chrome

**Comment by jbphet** [comment]
There was a bug in `PointControllerNode` where it wasn't adjusting its z-order when the value of a point that it was controlling upon construction was changed.  I've fixed this.

**Comment by jbphet** [comment]
I reviewed the modified behavior with @amanda-phet and @kathy-phet, and they are good with the change.

**Comment by KatieWoe** [comment]
Looks good in rc.2
